### ISSUE TITLE
egenskab i dcat:CatalogRecord - udgivelsesdato eller tilføjelsesdato?

### ISSUE THREAD

**Issue by laers** [digst/DCAT-AP-DK#13]
Afsnit 4.2.2 i specifikationsdokumentet omhandler egenskaben "tilføjelsesdato", men i diagrammet hedder egenskaben "udgivelsesdato" - ensrettes?
![image](https://user-images.githubusercontent.com/34093019/80222813-ace96b80-8647-11ea-8a65-5db2f2fb883d.png)

**Comment by aidig** [comment]
Tak for beskeden Lars!

Selvom oversættelsen af kernemodelelementet "dct:issued" har  oversættelsen "udgivelsesdato", så er det muligt i anvendelsesprofiler at angive anvendelsesorienterede betegnelser. 
I DCAT-AP anvender man faktisk også forskellige betegnelser for dct:issued:
* på Catalog = Release date, 
* på CatalogRecord = Listing date, 
* på Dataset = Release date, 
* på Distribution = Release date, 
Denne lille variation i katalogposten har vi bibeholdt, men måske kunne vi tage en generel vending på denne problemstilling.

**Comment by laers** [comment]
Ok, tak Anna. Det giver mening - troede det var en skrivefejl.

**Comment by aidig** [comment]
dct:modified har betegnelsen 'update/modification date' i DCAT-AP og her er den danske betegnelse desværre ikke lige konsekvent...  
Her tænker jeg at vi skal anvende 'seneste ændringsdato', ikke? 
... jeg retter til ...

**Comment by aidig** [comment]
måske skulle vi (indtil den danske oversættelse er helt på plads) også vise de engelske betengelser i de blå elementbokse?
