### ISSUE TITLE
Dansk betegnelse for dct:conformsTo

### ISSUE THREAD

**Issue by pebran** [digst/DCAT-AP-DK#14]
Aktuelt er dct:conformsTo oversat til 'overensstemmelse'. 
Enten skal den danske betegnelse udvides til 'i overensstemmelse med' eller også (bedre) skal den ændres til 'overholder'. 
Sidstnævnte er både kortere og præcist.

DCAT-APs beskrivelse af egenskaben er: 
"This property refers to an Application Profile that the Dataset’s metadata conforms to"

**Comment by aidig** [comment]
Dette issue er behandlet i https://github.com/digst/DCAT-AP-DK/issues/9 (og lukkes her)
