### ISSUE TITLE
langString vs literal

### ISSUE THREAD

**Issue by JanEmilLarsen** [digst/DCAT-AP-DK#34]
Er det korrekt forstået at den danske DCAT-AP-DK er skærpet ift. DCAT-AP, således at strenge er fastlagt til typen (range) _rdf:langString_ i AP-DK, mens der alene kræves _rdsf:Literal_ i AP.

Medfører det at angivelser altid kræves at have sprogangivelse, altså fx "Dataset"@en, mens "Dataset" ikke er en lovlig værdi.
Måske kan svarer deles via FAQ'en

**Comment by JanEmilLarsen** [comment]
Det ser ud som om anvendelsen af rdf:langString alene er specificeret i EAPX-UML-modellen; det autoritative dokument (?) 

https://digst.github.io/DCAT-AP-DK/releases/v.2.0/docs/

nævner ikke anvendelsen af det skærpe udfaldsrum ...

Betyder det at man er DCAT-DK-compliant selvom man ikke implementerer rdf:langString?

**Comment by aidig** [comment]
Uoverensstemmelse i udfaldsrum for tekstuelle egenskaber mellem specifikationstekst og UML-diagram, vil blive rettet i patch (DCAT-AP-DK 2.0.2). 

Rækkevidden for egenskaberne skos:prefLabel, dct:title, dct:description, dcat:keyword,foaf:name vil være xsd:string. Spectekst opdateret - billedfiler på vej.

Dette issue lukkes dermed.
